import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import StateProvider from "./context/StateContext";
import Nav from "./components/nav";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>L2VE</title>
        <meta
          name="description"
          content="Cupid Inu has landed on BASE! His mission is to scatter as much $L2VE as possible. For this mission he travels from one L2 blockchain to the next."
          key="desc"
        />
      </head>
      {/* <body
        className={`bg-gradient-to-b from-white via-[#0052FF]/30 to-[#0052FF] ${poppins.className}`}
      > */}
      <body
        className={`bg-main bg-cover bg-no-repeat bg-[center_top_-100px] ${poppins.className}`}
      >
        <StateProvider>
          <Nav />
          {children}
        </StateProvider>
      </body>
    </html>
  );
}
